name       : glm
version    : 0.9.9.3
release    : 3
source     :
    - https://github.com/g-truc/glm/archive/0.9.9.3.tar.gz : fba9fd177073a36c5a7798c74b28e79ba6deb8f4bb0d2dbfc0e207c27da7e12c
license    : MIT
component  : programming.library
summary    : OpenGL Mathematics library
description: |
    C++ mathematics library for 3D software based on the OpenGL Shading Language (GLSL) specification.
patterns   :
    - /
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check