name       : glm
version    : 0.9.9.5
release    : 4
source     :
    - https://github.com/g-truc/glm/archive/0.9.9.5.tar.gz : 5e33b6131cea6a904339734b015110d4342b7dc02d995164fdb86332d28a5aa4
license    : MIT
component  : programming.library
summary    : OpenGL Mathematics library
description: |
    C++ mathematics library for 3D software based on the OpenGL Shading Language (GLSL) specification.
patterns   :
    - /
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
