name       : glm
version    : 0.9.8.2
release    : 1
source     :
    - https://github.com/g-truc/glm/archive/0.9.8.2.tar.gz : 430cc444881750622040f386b1e509c238f4813a58e069f9e39d3e3e7b73b629
license    : MIT
component  : programming
summary    : OpenGL Mathematics library
description: |
    C++ mathematics library for 3D software based on the OpenGL Shading Language (GLSL) specification. 
patterns   :
    - /
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
